create table tb_cargo (
    codigo int generated by default as identity,
    descricao varchar(255) not null,
    primary key (codigo)
);

create table tb_rubrica (
    id int generated by default as identity,
    descricao varchar(255) not null,
    tipo_rubrica varchar(1) not null,
    primary key (id)
);

create table tb_funcionario_pessoal (
    matricula int not null,
    nome_completo varchar(255),
    numero_cpf varchar(11),
    numero_rg varchar(20),
    telefone varchar(15),
    email varchar(255),
    primary key (matricula)
);

create table tb_funcionario_funcional (
    matricula int not null,
    cargo_id int not null,
    valor_salario numeric(12,2),
    primary key (matricula),
    foreign key (cargo_id) references tb_cargo (codigo),
    foreign key (matricula) references tb_funcionario_pessoal (matricula)
);

create table tb_dependente (
    matricula int not null,
    sequencia int not null,
    nome_completo varchar(255),
    numero_cpf varchar(11),
    nome_mae varchar(255),
    primary key (matricula, sequencia),
    foreign key (matricula) references tb_funcionario_pessoal (matricula)
);

create table tb_folha (
    ano int not null,
    mes int not null,
    matricula int not null,
    rubrica_id int not null,
    valor numeric(12,2) not null,
    primary key (ano, mes, matricula, rubrica_id),
    foreign key (matricula) references tb_funcionario_pessoal (matricula),
    foreign key (rubrica_id) references tb_rubrica (id)
);